### PR TITLE
Rename PMC -> PathMoveChange

### PR DESCRIPTION
**Pull request by jhprinz**

### CODE REVIEW

**Comment by jhprinz** [comment]
ready if it passes

**Comment by jhprinz** [comment]
@dwhswenson 

The build failed somehow with the outer lambda. Can you have a look that this is not caused by insufficient statistics?
```
>>> IndexError ("index 31 is out of bounds for axis 0 with size 31")
    IndexError                                Traceback (most recent call last)
    <ipython-input-10-0aefa0f5c512> in <module>()
    ----> 1 mistis.rate_matrix(storage.steps, force=True)
    
    /home/travis/miniconda2/envs/_test/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/analysis/network.pyc in rate_matrix(self, steps, force)
        772                 # probability automatically
        773 
    --> 774             rate = trans.rate(steps)
        775             self._rate_matrix.set_value(trans.stateA, trans.stateB, rate)
        776 
    /home/travis/miniconda2/envs/_test/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/analysis/tis_analysis.pyc in rate(self, steps, flux, outer_ensemble, outer_lambda, error, force)
        479         outer_cross_prob = self.histograms['max_lambda'][outer_ensemble]
        480         if outer_lambda is None:
    --> 481             outer_lambda = guess_interface_lambda(outer_cross_prob)
        482             # lambda_bin = -1
        483             # outer_cp_vals = outer_cross_prob.reverse_cumulative().values()
    /home/travis/miniconda2/envs/_test/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/analysis/tis_analysis.pyc in guess_interface_lambda(crossing_probability, direction)
         48     if direction > 0:
         49         cp_vals = crossing_probability.reverse_cumulative().values()
    ---> 50         while (abs(cp_vals[lambda_bin+1] - 1.0) < 1e-10):
         51             lambda_bin += 1
         52         outer_lambda = crossing_probability.bins[lambda_bin]
    IndexError: index 31 is out of bounds for axis 0 with size 31
```

**Comment by dwhswenson** [comment]
It is insufficient sampling. (Or a very bad choice of outer interface, but not in this case.)

We try to identify the lambda at the outermost interface by seeing where the crossing probability for that interface drops below 1. If it never drops below 1 (well, `1.0 - 1e-10`), you get this error.

This occurs because 100% of paths in the outermost ensemble go to the final state. That, in turn, means that either:

* you choose your outermost lambda very poorly
* you didn't sample your outermost interface enough

(Obviously, in this specific case, the problem is sampling. Laying out the whole explanation to be clear.)

**Comment by jhprinz** [comment]
Thanks. I was hoping it is...

**Pull request merged**
