### PR TITLE
Exclude object in fallback from storage

### PR DESCRIPTION
**Pull request by jhprinz**
As discussed in #620 this will implement the default exclusion of objects that are already stored in
the fallback. It can be turned of by

``` py
storage.exclude_from_fallback = False  # default is `True`
```

Same can be switched on for proxy objects that are neither stored in the fallback or the storage itself.

``` py
storage.exclude_proxy_from_other = True  # default is `False`
```

This way you can simple continue with a second file and not worry about storing objects again. This comes at a little performance overhead for checking in the fallback but that should be minimal.

### CODE REVIEW

**Comment by jhprinz** [comment]
@sroet Could you have a look at the example notebook in this PR and see, if that is what you want or need?

**Comment by sroet** [comment]
It look like It works the way I expected it to work. However, would this work for fallback 'chains' (eg. a tps run of 100 steps with a new storage every 25 steps where the new storage has the previous as fallback)?
Looking at code it only checks if ```store.fallback == obj._store```(line 879 in  openpathsampling/netcdfplus/objects.py )

 This would be False if I'm looking for something that is actually in the fallback of the fallback (of the fallback ... etc.), right? Please correct me if I misinterpreted that line of code

**Comment by jhprinz** [comment]
Yes, correct. Good catch. I thought that would already work by recursion, but I am not using the correct functions. Fixed this already, but am checking a little more. Why some things are not as fast as it should be.

**Comment by dwhswenson** [comment]
@jhprinz : what's the status on this? @sroet is starting to need it! :-)

**Comment by jhprinz** [comment]
Just updated it... Ready for review. I think there could be more testing though... Got ahead if you think this is okay. The bigger update will come soon, but this makes it possible what @sroet needs.

**Comment by dwhswenson** [comment]
This looks good, but I'm not entirely sure I understand `exclude_proxy_from_other`. Can you explain that a little more? I think this comes into play for the second case I describe below; I'm not sure when you would want to turn that behavior off.

Here's the behavior I would expect by default; does this represent the way it works?

* if `fallback` is set, and you try to save an object that exists in the fallback chain, then the object isn't saved
* if `fallback` is not set, you would re-save all objects to the new file

The first example is if I'm splitting my simulation over multiple files sequentially (due to limitations on disk space or wall time).

The second example is when I'm setting up a new simulation based on an old one (e.g., copying snapshots from a TPS run to be used for a committor analysis). 

I'll merge this, but some clarification would be helpful!

**Comment by jhprinz** [comment]
`exclude_proxy_from_other` was an idea that I had. A proxy object must reference a store from where you can load the object. So, if you store a proxy this is usually excluded, but only if the store that is referenced is the save as the one you want to store it in.

So, you can now tell what is supposed to happen in this case. Do you want to load the proxy object and re-save it or just keep the reference and assume that the user will take care of it.

Note that this case is only used when the object is also not in the fallback. So you have this reasons not to store an object

1. If the `__uuid__` exists in the current store
2. If the `__uuid__` exists in the fallback and `exclude_from_fallback=True`
3. If the `__uuid__` is marked using `store.remember(obj)`
4. If the object is a proxy and the store reference is the current store
5. If the object is a proxy and `exclude_proxy_from_other=True`

**Pull request merged**
