### PR TITLE
fix bug when getting the name of the function used to define the cv

### PR DESCRIPTION
**Pull request by ajsilveira**
func_name is not an attribute of FunctionCV

### CODE REVIEW

**Comment by dwhswenson** [comment]
Actually, this is a Python 2.7/3.x issue; the issue is with the function that the `FunctionCV` is wrapping around. See https://docs.python.org/3/whatsnew/3.0.html#operators-and-special-methods. We still support Python 2.7, so this should be set up in a way that works in both 2.7 and 3.x. You probably need something like this (at the top of the file; module-level):

```python
if sys.version_info > (3, ):
    get_callable_name = lambda c: c.__name__
else:
    get_callable_name = lambda c: c.func_name
```

(then use `get_callable_name` to get the name).

Also, I assume that you found this because something happened that raised an error message (since this is in an error message). I just wrote up some docs on making CVs that will, I hope, make it a little clearer! See #831.

**Comment by ajsilveira** [comment]
Yes. I was not importing the modules. Thanks for that link!.

**Comment by dwhswenson** [comment]
Please note that we have changed to the OPS license from LGPL (2.1 or later) to MIT. For any pull request to OPS that was started while the license was still LGPL, I need an explicit confirmation that you approve of the license change. Please add a comment with something like "The changes in this pull request are licensed under the MIT license."

**Comment by ajsilveira** [comment]
The changes in this pull request are licensed under the MIT license.

**Pull request merged**
