### PR TITLE
[WIP] Count MD steps run in EngineMover

### LINKED ISSUE #292: Counting MD steps run in each PMC
It would be really nice if each path mover (or at least each path mover that uses an engine) could report the number of MD integration steps it ran. If comparing the efficiency of two methods, I think the best approach is to use the number of MD steps as a measure of the total effort (it assumes overhead from everything else is can be made negligible, but is also independent of the computing platform).

From a user-facing standpoint, this might be best as a property of a PMC. I see it like this:

```python
>>> pmc.n_timesteps_used
{ engine1 : 125 }
```

I suggest a dictionary return value in case multiple engines are used.

Internally, that would probably be something like:

```python
# in PathMoveChange:
@property
def n_timesteps_used(self):
    self.mover.n_timesteps_used(self) # maybe takes self.details?
```

where the implementer of the path mover has implemented the `pathmover.n_timesteps_used(pmc)` to get the number of MD steps taken during a given pmc. 

For PMCs with sequential subchanges, the correct answer is of course to add to any key that already exists:

```python
@property
def n_timesteps_used(self):
    sub_counts = [sub.n_timesteps_used for sub in self.subchanges]
    # this implementation avoids branching
    engines = set(sum(sub_counts.keys(), []))
    step_count = {e : 0 for e in engines} 
    for sub_count in sub_counts:
        for engine in sub_count:
            step_count[engine] += sub_count[engine]
    return step_count
```

(or at least something like that should work)

By making all of this a property, we require no additional storage, and implementers of path movers just need to add one function to get the correct value. It also has the nice side effect that, if a user implements a path mover without implementing this function, and only discovers the mistake *after* running a huge calculation, then (assuming everything needed was stored in the `pmc.details`) the user can add this to the code after the fact and use the existing computational results.

### PR DESCRIPTION
**Pull request by dwhswenson**
Resolves #292. 

In principle, I think the 2-line fix in here does the job. However, I'll add some testing for it later.

### CODE REVIEW

**Comment by dwhswenson** [comment]
Correction ... current stuff does a limited implementation of the goal. The idea proposed in #292 is better than what I've implemented so far here. But this is a necessary start.

**Comment by jhprinz** [comment]
Can we move this to an issue. Only if we abandon this PR anyway and will create a new one later.

**Comment by dwhswenson** [comment]
> Can we move this to an issue. Only if we abandon this PR anyway and will create a new one later.

The PR is still pretty close to up-to-date. No reason to abandon it.

(Already mentioned this in person, but adding for the record)

**Comment by dwhswenson** [comment]
Closing this as outdated and unlikely to be cleaned up for merge (more likely to be completely rewritten). The linked issue is suggests a better implementation than what was started here.

**Pull request closed without merging**
