### PR TITLE
[WIP] Python 3 compatibility 

### PR DESCRIPTION
**Pull request by dwhswenson**
For some collaborative stuff I'm working on with the PyRETIS devs, we needed OPS to become Python 3 compatible (PyRETIS is py3-only). So I've spent the last couple days updating OPS to add Python 3 support.

- [x] Update Travis script to test py-2.7 and py-3.6
- [x] Fix nosetests to work with both 2.7 and 3.6
- [ ] Fix notebook tests to work with both 2.7 and 3.6
- [ ] Check all local notebooks
- [ ] Clean up any automated additions (especially in testing: zip, range, old_div)

Note that it might be worth spending some time double-checking performance on some of these changes. @jhprinz, I assume you'll tell me if you see anything that might be a performance killer, especially with the significant changes in making netcdfplus/storage ready for Python 3.

### CODE REVIEW

**Comment by dwhswenson** [comment]
Where it stands right now:

* Remaining test failures look to me like they're storage-related (guessing issues with unicode vs byte strings?) @jhprinz, could you look into those and see if you can find an easy fix? 20 tests fail with errors in Python 3 (out of 707 total tests), but it looks like only 4 distinct errors are raised.
* Haven't checked what happens if I try our ipynbs using Python 3 (will wait until storage works properly). @jhprinz: I think ipynbtest is Python 3 ready, but is there a conda-installable Python 3 version? I seemed to have trouble the one time I tried to install it in the Python 3 test environment.
* I used `futurize` to update our tests (but only the tests). I need to go through the diffs and see what things were redundant.

At this point, we can do some experimental stuff with the PyRETIS collaboration, but the useful stuff will only happen once we can use storage with Python 3.

**Comment by jhprinz** [comment]
Will have a look this evening, if it will not be too late. I think it is not that big of a problem, but no promises here that I will fix it today. But create that you collaborate again!!!!!!!

**Comment by dwhswenson** [comment]
Thanks @jhprinz : and no stress about a 1-day fix. I hope it'll be easy, though.

We're already to the point where this branch can be used to work on making it possible to convert between OPS and PyRETIS for some parts of simulation setup (CVs) and for analysis. Of course, we can write tests of that without reading files, but it's only really useful to a user if we can read files! :-)

**Comment by dwhswenson** [comment]
Note: this also removes the pin to hdf 4.2.12, which was recently fixed (see https://github.com/ContinuumIO/anaconda-issues/issues/1360)

**Comment by dwhswenson** [comment]
Task list for making the notebooks in examples/tests/ work with Python 3:

- [ ] `langevin_integrator_check.ipynb`
- [ ] `storage_mem_test.ipynb`
- [ ] `test_cv.ipynb`
- [ ] `test_netcdfplus.ipynb`
- [ ] `test_openmm_integration.ipynb`
- [ ] `test_pyemma.ipynb`
- [ ] `test_snapshot.ipynb`
- [ ] `test_snapshot_modifier.ipynb`
- [ ] `test_storageview.ipynb`

**Comment by dwhswenson** [comment]
@jhprinz : `examples/tests/test_storageview.ipynb` requires a file `trajectory.nc`, which we don't say how to make. Should that filename be changed? Or should that whole notebook be removed (and maybe replaced with a unit test, so we can see the coverage)?

**Comment by dwhswenson** [comment]
Task list for notebooks in `examples/misc/`:

- [ ] `committors.ipynb`
- [ ] `custom_strategy_repex_shoot_repex.ipynb`
- [ ] `fun_with_pathmovers.ipynb`
- [ ] `move_strategies_and_schemes.ipynb`
- [ ] `tutorial_handle_nan.ipynb`
- [ ] `tutorial_movetree_visualization.ipynb`
- [ ] `tutorial_path_histogram.ipynb`
- [ ] `tutorial_pathtree_visualization.ipynb`
- [ ] `tutorial_storage.ipynb`

**Pull request merged**
