### PR TITLE
OpenPathSampling 1.5

### PR DESCRIPTION
**Pull request by dwhswenson**
OpenPathSampling 1.5 is a significant release, including many new features and enhancements. Highlights of this release are the implementation of [Spring Shooting](http://dx.doi.org/10.1063/1.4965882) and the development of new "hooks" where users can patch in custom code during the simulation process, enabling much greater flexibility.

Note that the hooks are still considered beta code, and therefore some aspects of that API may change;

**DEPRECATION:** As of OPS 1.5, `MDTrajTopology` should be imported from `openpathsampling.engines`, not from `openpathsampling.engines.openmm`.

## New features and enhancements

* Spring Shooting mover/move scheme ([#850](https://github.com/openpathsampling/openpathsampling/pull/850) @sroet)
* "Hooks" to enable more simulation flexibility ([#755](https://github.com/openpathsampling/openpathsampling/pull/755), [#911](https://github.com/openpathsampling/openpathsampling/pull/911) @hejung)
* Gracious Kill Hook ([#914](https://github.com/openpathsampling/openpathsampling/pull/914) @hejung)
* Warn if CVDefinedVolume CVs return iterables ([#1030](https://github.com/openpathsampling/openpathsampling/pull/1030))
* Shooting point selector with arbitrary bias ([#1024](https://github.com/openpathsampling/openpathsampling/pull/1024))
* Add global random number generator; support in shooting pt selectors and pathmovers ([#998](https://github.com/openpathsampling/openpathsampling/pull/998) @sroet, [#1008](https://github.com/openpathsampling/openpathsampling/pull/1008) @sroet [#1015](https://github.com/openpathsampling/openpathsampling/pull/1015))
* Move n_dofs to engine; add engine.has_constraints() ([#979](https://github.com/openpathsampling/openpathsampling/pull/979))

## Experimental (beta) features

* SimStore: Periodic CVs ([#990](https://github.com/openpathsampling/openpathsampling/pull/990))
* SimStore: Make storable function modes customizable ([#1004](https://github.com/openpathsampling/openpathsampling/pull/1004))
* SimStore bug fixes and minor improvements ([#985](https://github.com/openpathsampling/openpathsampling/pull/985), [#995](https://github.com/openpathsampling/openpathsampling/pull/995), [#1002](https://github.com/openpathsampling/openpathsampling/pull/1002), [#1003](https://github.com/openpathsampling/openpathsampling/pull/1003), [#1016](https://github.com/openpathsampling/openpathsampling/pull/1016), [#1027](https://github.com/openpathsampling/openpathsampling/pull/1027)) #bugfix 

## Bugs fixed
* Make histogramming more robust ([#1029](https://github.com/openpathsampling/openpathsampling/pull/1029) @sroet)
* Fix problem with repeated ensemble names in MISTIS ([#988](https://github.com/openpathsampling/openpathsampling/pull/988))
* Fix MISTIS minus ensemble not forbidding other states ([#983](https://github.com/openpathsampling/openpathsampling/pull/983))
* Fix problem with Histogram.bin_range not getting set ([#972](https://github.com/openpathsampling/openpathsampling/pull/972))

## Miscellaneous improvements

* Move MDTrajTopology into `engines.topology` ([#1012](https://github.com/openpathsampling/openpathsampling/pull/1012) @sroet, [#1014](https://github.com/openpathsampling/openpathsampling/pull/1014)) #Deprecations
* Reduce unnecessary object creation ([#975](https://github.com/openpathsampling/openpathsampling/pull/975), [#976](https://github.com/openpathsampling/openpathsampling/pull/976) @sroet, [#978](https://github.com/openpathsampling/openpathsampling/pull/978) @sroet)
* Fix problems with PyEMMA tests ([#997](https://github.com/openpathsampling/openpathsampling/pull/997), [#1009](https://github.com/openpathsampling/openpathsampling/pull/1009), [#1018](https://github.com/openpathsampling/openpathsampling/pull/1018) @sroet, [#1022](https://github.com/openpathsampling/openpathsampling/pull/1022) @sroet, [#1023](https://github.com/openpathsampling/openpathsampling/pull/1023) @sroet)
* make test less flaky ([#999](https://github.com/openpathsampling/openpathsampling/pull/999) @sroet)
* Switch notebook tests to nbval ([#987](https://github.com/openpathsampling/openpathsampling/pull/987))
* Add automatic testing against OpenMM release candidates ([#1019](https://github.com/openpathsampling/openpathsampling/pull/1019), [#1020](https://github.com/openpathsampling/openpathsampling/pull/1020), [#1021](https://github.com/openpathsampling/openpathsampling/pull/1021))
* Improve interactions with CodeCov ([#980](https://github.com/openpathsampling/openpathsampling/pull/980), [#991](https://github.com/openpathsampling/openpathsampling/pull/991), [#1025](https://github.com/openpathsampling/openpathsampling/pull/1025))
* Improvements to the documentation ([#939](https://github.com/openpathsampling/openpathsampling/pull/939), [#970](https://github.com/openpathsampling/openpathsampling/pull/970), [#1010](https://github.com/openpathsampling/openpathsampling/pull/1010) @sroet)
* Pin OpenMM != 7.5.1 ([#1017](https://github.com/openpathsampling/openpathsampling/pull/1017))
* Pin sqlalchemy!=1.4.0 ([#996](https://github.com/openpathsampling/openpathsampling/pull/996))
* Add Python 3.8, 3.9 to testing matrix ([#993](https://github.com/openpathsampling/openpathsampling/pull/993))
* fix numpy 1.20 DeprecationWarnings ([#974](https://github.com/openpathsampling/openpathsampling/pull/974))

### CODE REVIEW

**Comment by dwhswenson** [comment]
My automatic release note writing code has some issues with large releases, which was compounded by [a change GitHub made](https://github.com/github/feedback/discussions/4321) which made manually creating these parts of these release notes a bit more of a headache. I'm hoping that contributors can double-check that all their contributions to this are included. From the commit list, that's @sroet and @hejung (and especially @sroet). If there are any PRs you've contributed to this release that got skipped in my manual process, please let me know. (Of course, release notes can also be edited later to correct things, so no worries if something slips through.)

I will leave this open for at least 24 hours, merging no earlier than Tue 06 Jul 19:00 GMT (15:00 my local). On merging, this should cut a new release (immediately on PyPI, expect a few hours before that makes its way to conda-forge).

**Comment by sroet** [comment]
LGTM, all PR's from me that have been updated since Jan 30 (last OPS release) and were merged into master are included.

One another note, we might want to add a place to track 2.0 release notes (so that things like #977 are not missed/forgotten)

**Comment by hejung** [comment]
LGTM! I dont recall any finished PRs from me except for the hooks stuff.
(Only the unfinished gromacs MDP parsing PR is still open from my side, which I will hopefully get to finish in the coming days but not in time for 1.5)

**Comment by dwhswenson** [comment]
Thanks! I'll merge this later today, once the promised comment time window runs out (just in case anyone else has comments -- not likely).

> One another note, we might want to add a place to track 2.0 release notes (so that things like #977 are not missed/forgotten)

We have a [2.0 label](https://github.com/openpathsampling/openpathsampling/issues?q=label%3A2.0) for that purpose. If I forget to label anything as 2.0 that should be, please let me know!

> (Only the unfinished gromacs MDP parsing PR is still open from my side, which I will hopefully get to finish in the coming days but not in time for 1.5)

No worries -- that one will be great to have, but isn't something I've promised elsewhere with a specific version number. Merging in hooks (promised for 1.5) a was big weight off my shoulders. The things I've promised for 1.6 are in the [1.6 milestone](https://github.com/openpathsampling/openpathsampling/milestone/14) (in particular #1001 and #1026), but of course there's room for other contributions to go in as well!

**Pull request merged**
