### PR TITLE
Split pathsimulator.py

### PR DESCRIPTION
**Pull request by dwhswenson**
As mentioned in #753, we should reorganize our file structure. I'm planning to do some work on parallelizing some path simulators soon, so I'm starting by reorganizing the `pathsimulator.py` file. Here's how I'm splitting it:

* `path_simulator.py`: `PathSimulator`, `MCStep` (will move MCStep elsewhere later)
* `shoot_from_snapshot.py`: `ShootFromSnapshotsSimulation`; `CommittorSimulation`
* `path_sampling.py`: `PathSampling`
* `bootstrap_init_conds.py`: all bootstrap stuff
* `direct_md.py`: `DirectSimulation`

Note that the approach I've used to split involves some git acrobatics in order to preserve history on lines within the split files. See https://beyermatthias.de/blog/2014/09/24/splitting-files-while-preserving-history-in-git/.

### CODE REVIEW

**Comment by dwhswenson** [comment]
Passes tests. Ready for review/merge.

**Comment by dwhswenson** [comment]
Thanks -- I have some rough plans for doing the same with `ensemble.py` and `pathmover.py`, and will do those later. Will merge this one now!

**Comment by sroet** [comment]
I would have liked an `API Break` or `module rename` label on this PR. 
It broke the import of `pathsimulator` by the renaming to `pathsimulators`. This change is also not mentioned in the comments.

**Comment by dwhswenson** [comment]
What were you importing from `openpathsampling.pathsimulator`? Isn't everything that is public also directly importable from the main `openpathsampling` namespace?

In order to make sure everything only shows up in only one place in the (official, public) API, I think that only the least-nested level should be used. For most of OPS, that means the root `openpathsampling` namespace.

**Comment by sroet** [comment]
@dwhswenson 
>What were you importing from openpathsampling.pathsimulator? Isn't everything that is public also directly importable from the main openpathsampling namespace?

You are correct, thanks for the tip. This came up in one of my old E-CAM modules (the transition state ensemble). It is now fixed, and imports from the  `openpathsampling` namespace.

**Pull request merged**
