### PR TITLE
Fix encryption keys

### PR DESCRIPTION
**Pull request by jhprinz**
Not sure, but I think, the problem is a misconfigured .travis.yml file not missing keys. Turns out that the keys are not set in the current script. This might fix it. Hard to test.

### CODE REVIEW

**Comment by jhprinz** [comment]
Try to merge it and see what happens...

**Comment by dwhswenson** [comment]
merging, with fingers crossed that this will fix it (no need to worry about tests; this only affects structure of the `.travis.yml`, and we won't know if it works until it is merged to master anyway)

**Comment by dwhswenson** [comment]
Excellent! This fixed it. Still have lots of warnings to fix in the docs build, but at least the docs are getting uploaded! (I really needed that, since I want the report I need to finish this week to point to the new docs on TIS analysis -- thanks for figuring out the problem and quickly fixing it!)

**Comment by jhprinz** [comment]
No way, really? Wow, that was a long shot... Great...

**Comment by dwhswenson** [comment]
I needed this to exist: http://openpathsampling.org/latest/topics/tis_analysis.html

Now it does! :-)

**Pull request merged**
