### PR TITLE
Remove things deprecated for 2.0

### PR DESCRIPTION
**Pull request by dwhswenson**
**ANNOUNCING THE DEV-2.0 BRANCH!**

If you have changes that must change the API, please target the `dev-2.0` branch. I'm starting that off by removing all deprecated functionality (at least, what I could find).

For most improvements and new functionality, please continue to target the default branch. Changes there will be merged into `dev-2.0` regularly. I expect that there will be several more releases of OPS (at least up to 1.6) before 2.0 is finalized.

### CODE REVIEW

**Comment by dwhswenson** [comment]
This is ready for review and comment. I will leave it open for at least 24 hours, merging no earlier than Fri 25 Dec 09:00 GMT (10:00 local).

**Comment by sroet** [comment]
This LGTM.
You might want to keep a change-log around to get a quick summary on what got dropped in which PR, but I will leave that up to you.

**Comment by dwhswenson** [comment]
> You might want to keep a change-log around to get a quick summary on what got dropped in which PR, but I will leave that up to you.

Not sure in which way you mean this... if in the sense of linking back to original PRs where the deprecations happened, that isn't trivial but isn't too hard: this PR dropped all deprecations to date, and anything that raises a deprecation warning says what version of OPS deprecated it (see removed code in this PR), so you can go to the release notes of that version to dig it up. A few steps, but not too bad when you know what to do.

If you mean in the sense of what happened leading to 2.0 that wasn't in 1.x, that's easier: that's the purpose of the 2.0 label. A click on that will list all such PRs, making release notes easy.

**Comment by sroet** [comment]
>  if in the sense of linking back to original PRs where the deprecations happened, that isn't trivial but isn't too hard: this PR dropped all deprecations to date, and anything that raises a deprecation warning says what version of OPS deprecated it (see removed code in this PR), so you can go to the release notes of that version to dig it up. A few steps, but not too bad when you know what to do.

This is what I meant, but I see that that should indeed be (very) doable with the version info in the deprecation  :)

**Pull request merged**
