### PR TITLE
Switch to GitHub Actions

### PR DESCRIPTION
**Pull request by dwhswenson**
This disables support for Travis CI and switches to GitHub actions. [Travis CI made significant changes](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) to its pricing plan that caused major havoc among open source projects. [Although Travis CI has reaffirmed their support of open source](https://blog.travis-ci.com/oss-announcement), their roll-out of the new model was an absolute mess (no warning, understaffed to deal with thousands of requests from OSS developers for more minutes). See [this thread on the Travis CI forums](https://travis-ci.community/t/org-com-migration-unexpectedly-comes-with-a-plan-change-for-oss-what-exactly-is-the-new-deal/10567) for some sense of the confusion. During the early uncertainty, I (and thousands of other devs) switched away from Travis. All of my projects other than OPS are now running on GitHub Actions, and so I'm moving OPS over to Actions as well.

The GitHub Actions workflows here have been tested in a separate branch, so they work. For an example, see tests on d7ee961.

To-do: Add support for building/deploying docs. That should come within a week or two (need to get some permissions, but in principle everything should be figured out).

For discussion: GitHub Actions may bring some more flexibility than we had with Travis. A few things I'm looking to try out:

* Different behaviors if a PR is marked as a draft. For example, don't run notebook tests in draft PRs (encouraging faster development cycle then).
* Separate testing aspects into different workflows: Perhaps move the notebook tests to run in parallel with unit tests. Perhaps have the docs build/deploy as a separate workflow that only happens after merging a PR.

On these points, I'm curious what contributors think. In particular pinging @sroet  and @hejung for any thoughts.

### CODE REVIEW

**Comment by dwhswenson** [comment]
Oh, and also I'm moving from Coveralls to CodeCov for coverage reports. I never liked the constructivism-inspired design of Coveralls, but it used to be that Coveralls was the best for handling parallel builds. Now I think that CodeCov does almost as well, and looks better. And I've finally given in and accepted getting a comment from CodeCov on each PR.

**Comment by sroet** [comment]
>    Different behaviors if a PR is marked as a draft. For example, don't run notebook tests in draft PRs (encouraging faster development cycle then).

I have no strong opinion on this (run the test suite on my own machine anyway), the one drawback I could think if the CI is not retriggered after someone just removes the `Draft` tag on a PR (normally editing the title does not retrigger the CI), therefor leading to a possible broken code after merging

>    Separate testing aspects into different workflows: Perhaps move the notebook tests to run in parallel with unit tests. Perhaps have the docs build/deploy as a separate workflow that only happens after merging a PR.

I'm always in favor of running as much parallel as allowed/socially accepted. I do think the notebook test, unit-test, doc building should be parallel jobs (especially if we don't want to run the docs or the notebooks for the whole test matrix)

Also, I would `build` docs on the PR (but maybe only if doc files changed?), but `deploy` should only be done from protected branches.

On this PR: the code looks decent (did not look too deeply at the autorelease-* vendored scripts). I would enable `3.8` testing soon as well, but you might want to do that in a different PR.

**Comment by dwhswenson** [comment]
> I have no strong opinion on this (run the test suite on my own machine anyway), the one drawback I could think if the CI is not retriggered after someone just removes the Draft tag on a PR (normally editing the title does not retrigger the CI), therefor leading to a possible broken code after merging

This is where GitHub actions may provide a little more flexibility (or, at least, better integration with GitHub) than other CI platforms can. Note activity types in the details of [how pull requests trigger workflows](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request). Also, you have access to the [whole JSON object for the PR](https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls) (from the REST API), which includes the boolean "draft" attribute. I'll have to experiment a bit, but I think it can be done such that notebook tests trigger when (1) you open/push to/reopen a PR that is not a draft; (2) you convert a PR from draft to ready-to-review.

> I'm always in favor of running as much parallel as allowed/socially accepted. I do think the notebook test, unit-test, doc building should be parallel jobs (especially if we don't want to run the docs or the notebooks for the whole test matrix)
> 
> Also, I would `build` docs on the PR (but maybe only if doc files changed?), but `deploy` should only be done from protected branches.

Thanks; these are both the direction I've been leaning, too.

For this PR, I'll may things more analogous to what we do on Travis, but it's good to hear feedback on what others would find useful in the future.

> I would enable `3.8` testing soon as well, but you might want to do that in a different PR.

Waiting on OpenMMTools. Just set up a conda env to see if I can fix their failing tests and encourage a conda-forge release, now that OpenMM is there.

**Comment by dwhswenson** [comment]
Since Travis seems to be dead (nothing is happening in #961), I'm going to go ahead and merge this one so we have CI. I'll add docs support later.

**Pull request merged**
