### PR TITLE
fixed caching_mode='unlimited'

### LINKED ISSUE #779: Storage: caching_mode='unlimited' does not work
The code:
```python
import openpathsampling as paths
storage = paths.AnalysisStorage('storagefile.nc', caching_mode='unlimited')
```
results in:
```
TypeError: 'dict' object is not callable
```

I think I found the problem and created a PR (#778) with a fix.

### PR DESCRIPTION
**Pull request by hejung**
See also the corresponding Issue #779 .

(Maintainer edit: closes #779)

### CODE REVIEW

**Comment by jhprinz** [comment]
@hejung @dwhswenson I think this can be merged. Obvious typo. Thanks for fixing it.

**Comment by dwhswenson** [comment]
Please note that we have changed to the OPS license from LGPL (2.1 or later) to MIT. For any pull request to OPS that was started while the license was still LGPL, I need an explicit confirmation that you approve of the license change. Please add a comment with something like "The changes in this pull request are licensed under the MIT license."

**Comment by hejung** [comment]
The changes in this pull request are licensed under the MIT license.

**Comment by dwhswenson** [comment]
@hejung : Could you do a rebase or merge our current master into this branch? I tried to re-run the CI just to be sure that it still worked (I mean, there's no way this would break anything, but always be safe). It appears re-running the build uses the `.travis.yml` from the original build. Our `.travis.yml` has changed since then, and the repo isn't compatible with the old Travis script. Thanks!

**Comment by hejung** [comment]
Done. Sorry for the delay.

**Comment by dwhswenson** [comment]
Thanks! Merging this.

**Pull request merged**
