### PR TITLE
Documentation cleanup

### LINKED ISSUE #490: Reorganize `examples` directory
As discussed a little in #482, we are all in agreement that the `examples` directory needs to be reorganized. Let’s figure out how to restructure it.

First point: does everyone agree with getting rid of the extra layer of `examples/ipython` and moving all the ipynb examples into the main `examples` directory? (All of our examples are ipynbs, the only other things in there will be initial information needed for startup, e.g., PDBs.)

Second: the structure within that directory. I gave a partial suggestion before, based on the idea that we would organize by system (toy, alanine dipeptide), then by method (TPS, TIS). @jchodera felt that it was better to organize by method, then by system.

I’ll put a proposal in the first comment below, and I’ll reserve this top post for description of the consensus.

## Consensus / Summary

* *do we move everything to `examples`?* (Agreed yes)
* *what overall structure do we decide on?* (Basically as below)

### PR DESCRIPTION
**Pull request by dwhswenson**
Our docs are in pretty bad shape: poorly organized and outdated. This does some significant cleanup, and imports (and organizes) several of our example notebooks.

- [x] Bring current (and useful!) examples into the openpathsampling.org docs
- [x] Modify the website so that examples are very easy to find
- [x] Move a few notebooks that are pure documentation from examples to the docs
- [x] Move less useful "miscellaneous" docs to the background (a "miscellaneous examples" page) 
- [x] Remove things (e.g. Langevin example) that have no pedagogic value (or instead shift to miscellaneous)
- [x] Start developer documentation: explanations of the code to help new devs. Might also be useful in writing paper 2.

Must merge *after* #571.

The first few tasks address @jchodera's remaining concerns about the examples directory (after the stuff from #588 is merged), so this PR closes #490.

### CODE REVIEW

**Comment by dwhswenson** [comment]
This is ready for review. Only affects the docs and reorganizes some examples (added some docstrings to the code, too.)

The docs are still far from perfect, but I suspect that will be an eternal goal. However, this is enough to move me away from my previous statement to people who were interested in OPS, which was "uh, go to the GitHub site, not openpathsampling.org." Now I think openpathsampling.org will be a better place to start than the GitHub examples.

Among the changes: most examples are now on the website, organized as "introductory", "advanced", "special topics", and "miscellaneous." Of course, we can switch examples from one to another within those.

Our sidebar used to contain a bunch of specific API stuff (e.g., "Storage Functions", "PathMover functions", etc.) I moved all of that to the heading "OpenPathSampling API". Now our sidebar consists of: "Installation," "Examples," "Guides," "Topics," "What's New?," "Frequently Asked Questions," "Overviews for Developers," and "OpenPathSampling API." All the old information is still available; I just tried to minimize what the user sees on first sight.

The "Overviews for Developers" is a new addition, which I've only started. I will also need help from @jhprinz to complete it (especially the storage and CV sections). These are explanations of the code aimed at, e.g., our ESDW developers. The "Code structure" section, which is a broad overview, is pretty close to done -- others, less so.

**Comment by jchodera** [comment]
Can you compile the docs into a PDF and upload that? I think it's just `make latexpdf`.

**Comment by dwhswenson** [comment]
Looks like it doesn't work. I think LaTeX doesn't like our `notebook` directive:

```
Exception occurred:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/writers/latex.py", line 2015, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: notebook_node
The full traceback has been saved in /var/folders/n1/lvkvzv_j57d92rnh6d4qn_zh0000gn/T/sphinx-err-ceMq__.log, if you want to report the issue to the developers.
```

The full log wasn't much more informative than that. I think our `notebook` directive is something that @jhprinz wrote/found, so it might have only included HTML support.

(BTW, I wasn't entirely clear on what you meant @jchodera : I assume you meant to attach it to a GitHub comment, since reading PDF is a lot easier than these miscellaneous RST diffs -- is that correct?)

**Comment by jhprinz** [comment]
> The full log wasn't much more informative than that. I think our notebook directive is something that @jhprinz wrote/found, so it might have only included HTML support.

This was inspired by what was used in mdtraj and it was a quick afternoon hack to include the notebooks. Maybe its time to make this a little better and robust against these changes. 

Otherwise I will merge this now. I will make a quick issue about the PDF docs.

**Pull request merged**
