### PR TITLE
kill off getslice

### PR DESCRIPTION
**Pull request by sroet**
As `list.__getslice__()` has been deprecated since python `2.0` and [killed since `3.0`](https://docs.python.org/3/whatsnew/3.0.html?highlight=list%20__getslice__#operators-and-special-methods) this also removes the `Trajectory` override of it.

### CODE REVIEW

**Comment by sroet** [comment]
@dwhswenson Do we want to keep python 2.7 support alive here (I don't have a python 2 environment anymore). If so, feel free to close this PR

**Comment by dwhswenson** [comment]
Our official commitment is to support Py27 until
OPS 2.0. This is to allow PhD students who started in 2.7 to finish with working code. (Hoping that's mainly @arjunwadhawan, who has now submitted his thesis!) Could you close and target this against `dev-2.0` instead?

**Comment by sroet** [comment]
@dwhswenson Github allows to change the base branch :smile: , so this should not be correct

**Comment by sroet** [comment]
do you want me to properly rebase onto dev-2.0, or don't you mind pulling the master/dev-2.0 diffs as well?

**Comment by dwhswenson** [comment]
Doesn't matter. I've been doing the occasional merge of master into dev-2.0. If I've fallen a bit behind, no worries if your PR catches me up. As long as contributors get the appropriate credit (which (1) they would with this; (2) not an issue in this specific case) then I'm happy.

**Review by dwhswenson — APPROVED** [review]
LGTM. There's a drop in coverage largely due to removing Py2.7 from the testing matrix (some code paths no longer used). I'll follow this up with a PR removing some of those code paths.

Related: note that part of the [roadmap to 2.0](https://github.com/openpathsampling/openpathsampling/wiki/Roadmap) includes modifying trajectory so that it no longer inherits directly from `list` (instead wrapping a list and inheriting from `collections.abc.Sequence`).

**Pull request merged**
