### PR TITLE
0.9.1 => 0.9.2

### PR DESCRIPTION
**Pull request by dwhswenson**
Version bump before release of 0.9.2.

### CODE REVIEW

**Comment by jhprinz** [comment]
Looks good.

I think the version.py file is actually written by setup.py, isn't it?

**Comment by dwhswenson** [comment]
That's `openpathsampling/version.py`. The one that got changed is `openpathsampling/netcdfplus/version.py`. You did the clever trick of faking into thinking it was already a separate package ;-)

**Comment by jhprinz** [comment]
Right... :)  So go ahead and bump to 0.9.2

**Comment by dwhswenson** [comment]
It has been released! Released like the Kraken!

**Pull request merged**
