### PR TITLE
enable py310 tests

### PR DESCRIPTION
**Pull request by sroet**
should be the only thing required to test https://github.com/conda-forge/openpathsampling-feedstock/pull/20

### CODE REVIEW

**Comment by dwhswenson** [comment]
Related: #1095 (written at same time! 😆)

I suspect the issues will be with the various optional requirements. These can be manually managed based on the value of Python version `CONDA_PY` by modifying `devtools/conda_install_reqs.sh`.

**Comment by sroet** [comment]
alright, so the first things required for this to work is openmm needs to have a python 3.10 build (conda search openmm comes up with nothing) 
do we want to add an issue on their tracker?

**Comment by dwhswenson** [comment]
> do we want to add an issue on their tracker?

No need -- they won't release one anyway until the 7.7 release (in RC now). That will be followed quickly by an OpenMMTools release, too (on mobile now, but there's an issue on their feedstock, IIRC).

**Comment by sroet** [comment]
this is waiting on:  https://github.com/conda-forge/openmm-feedstock/pull/68 or some equivalent

**Comment by dwhswenson** [comment]
Tried re-running this today. Looks like there still isn't a Python 3.10 build on OpenMM on conda-forge. See https://github.com/conda-forge/openmm-feedstock/pull/68. Currently looks like there are problems with pypy on aarch64  CPython 3.10 on win.

**Comment by dwhswenson** [comment]
(And apparently we both found that within about 10 seconds of each other 😆)

**Comment by sroet** [comment]
retriggering CI as openmm is now available for python 3.10

**Comment by sroet** [comment]
This is now waitng for a pyemma release for python 3.10

**Comment by dwhswenson** [comment]
Superseded by #1133.

**Pull request closed without merging**
