### PR TITLE
Fix loading `Named` from cache

### PR DESCRIPTION
**Pull request by jhprinz**
Loading of named objects was inefficient and always loaded and fixed the name attribute. This fixes this.

### CODE REVIEW

**Comment by jhprinz** [comment]
Yeah. I finish the 400 GB with this PR yesterday. Loading and analysis took < 45 min. Now we are in buisiness. Expect the Ala Example soon!

**Comment by dwhswenson** [comment]
This is still failing on Travis... problem with `test_openmm_integration.ipynb`. I just re-ran the last travis build on master, and that works fine, so the problem must be somewhere in this PR, not in a change with an upstream library.

**Comment by bolhuis** [comment]
Wow that is fantastic news! Great work.

P

**Comment by jhprinz** [comment]
Found the problem will fix this now.

**Comment by dwhswenson** [comment]
... does `conda --yes` no longer work?!?!

**Comment by jhprinz** [comment]
no, seemed to work no sure what happened. But strangely my local version is fixed, but the travis version still has the same error... I am puzzled

**Comment by jhprinz** [comment]
No, wait... ??? That is strange...

**Comment by dwhswenson** [comment]
I noticed it was happening on all the builds, too. `conda create --yes` and the `--yes` is being ignored. New `conda` version with a bug?

nightlies on choderalab/perses and choderalab/ensembler have the same problem. Problem seemed to start >5 hours ago, <6 hours ago, based on last passed nightlies of projects I know.

**Comment by dwhswenson** [comment]
https://github.com/conda/conda-build/issues/1825

**Comment by dwhswenson** [comment]
Looks good to me now (reviewed code as it stands currently). My main concern in this part of the code is performance, and it sounds like this will make it a *lot* better! @jhprinz, is this ready for merge?

**Comment by jhprinz** [comment]
Yes, ready to be merged and should improve performance a lot. (Not saying that there is no more room for improvements :) Go ahead

**Comment by dwhswenson** [comment]
Merging!

**Pull request merged**
