### PR TITLE
Rename live visualization

### PR DESCRIPTION
**Pull request by dwhswenson**
- [x] `LiveVisualization` => `StepVisualizer2D`
- [x] `PathSampling.live_visualization` => `PathSampling.live_visualizer`
- [x] `PathSampling.visualization_frequency` => `PathSampling.status_update_frequency`
- [x] Update notebooks used in tests
- [x] Update remaining notebooks (requires #588)

See also #527.

Note that this now includes #588, which should be merged first.

Fixes this everywhere except in AD TPS examples; that will be added to #571.

### CODE REVIEW

**Comment by dwhswenson** [comment]
Passes tests, ready for review. Includes #597, #588, so please handle those first (will try to update after #588 is merged, to make review here easier.)

**Comment by jhprinz** [comment]
@dwhswenson  #588 is merged you can update

**Comment by jhprinz** [comment]
Although I think there is not much to review...

**Comment by dwhswenson** [comment]
@jhprinz: updated. You're correct: There is not much to review. :-) But doing the update definitely makes it easier to look over!

Tests still running as I type this, but barring 5000-step error, it should pass (other stochastic errors should be solved!)

**Comment by jhprinz** [comment]
Good. Merging...

**Pull request merged**
